### ISSUE TITLE
배고파요

### ISSUE THREAD

**Issue by ltlapy** [ltlapy/misskey#8]
## 💡 Summary
배가 매우 고픕니다.
제가. 아주. 엄청. 많이.

## 🥰 Expected Behavior
- 포만감과 행복에 가득 둘러쌓여있다

## 🤬 Actual Behavior
- 매우 허기지고 안절부절하다
- 공복감이 위장을 지배하고 있다

## 📝 Steps to Reproduce

1. 아침 7시 반에 일어난다
  > **Warning** 음주 및 야식을 하지 않고, 충분한 숙면을 취하도록 합니다.
2. 아침 8시에 식사를 한다
3. 오후 4시까지 기다린다

## 📌 Environment

부산집. 냉장고에 오징어 젓갈이랑 계란장, 오늘 아침에 막 만든 시금치 나물이 있다. 밥솥에는 오늘 아침에 지은 밥이 약 2인분 남아있다.

**Comment by ltlapy** [comment]
아아아아아ㅏㅇ니 그러면 식사를 하세요!

**Comment by ltlapy** [comment]
뭐먹지
- 라면
  - 너구리 순한맛 x5
  - 짜장라면 x5
  - 돈코츠 라멘 x1
  - 간장맛 비빔면 x1
- 집에 있는 반찬과 된장국
- *~~배달~~*
  - 금월 예산 부족

조건: 2인분 식사를 차려야 합니다

**Comment by ltlapy** [comment]
>그보다 굳이 GitHub 이슈로 다루어야 할 사안인가요!

**네, 그렇습니다!** 밥을 삼시세끼 제대로 챙겨먹는 건 중요하니까요.
<img width="420" alt="image" src="https://user-images.githubusercontent.com/19978840/222948162-44078eed-1a20-4e90-b2ee-13293658eaea.png">

**Comment by ltlapy** [comment]
> 뭐먹지
> 
> * 라면
>   
>   * 너구리 순한맛 x5
>   * 짜장라면 x5
>   * 돈코츠 라멘 x1
>   * 간장맛 비빔면 x1
> * 집에 있는 반찬과 된장국
> * _~배달~_
>   
>   * 금월 예산 부족
> 
> 조건: 2인분 식사를 차려야 합니다

집에 있는 반찬과 계란후라이를 합시다. 이따가 간식이라도 먹자구요.
시간이 없으니 바로 착수합니다

**Comment by ltlapy** [comment]
https://k.lapy.link/notes/9bynrlnsgj

**Comment by Canorus** [comment]
해결책 가운데 밀면이 누락됨. 보강이 요망되 는상황.

**Comment by ltlapy** [comment]
> 해결책 가운데 밀면이 누락됨. 보강이 요망되 는상황.

이 시기에는 밀면을 많이 먹지 않았습니다. 추후 업데이트 재개 시 갱신을 고려하겠습니다.
또한, 현재 이 Repository는 더 이상 유지보수되고 있지 않은 점 양해 바랍니다.
